graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "A"
      graphics [
         x 102
         y 198
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 274
         y 127
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 498
         y 137
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 497
         y 327
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 788
         y 356
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 854
         y 186
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 5
      label ""
      weight 1.0
   ]
]