graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 533
         y 126
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 790
         y 291
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 723
         y 543
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 436
         y 521
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 342
         y 297
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 557
         y 354
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 1
      label ""
      weight 1.0
   ]
]