graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 592
         y 112
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 481
         y 241
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 681
         y 244
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 370
         y 351
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 463
         y 368
      ]
   ]
   node [
      id 9
      label "N"
      graphics [
         x 542
         y 354
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 658
         y 340
      ]
   ]
   node [
      id 13
      label "N"
      graphics [
         x 747
         y 344
      ]
   ]
   node [
      id 15
      label "N"
      graphics [
         x 848
         y 312
      ]
   ]
   edge [
      source 1
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 15
      target 3
      label ""
      weight 1.0
   ]
]